### PR TITLE
Web Implemented

### PR DESCRIPTION
**Pull request by JohnGalt1717**
This code enables full web support for screen capture with audio. It outputs webm since that's what chrome supports.

### CODE REVIEW

**Comment by salime45** [comment]
Hi @JohnGalt1717 , 

Sorry for the late, i tried the app right now. Works perfectly. Thanks for your job .

Do you know if the screen record and audio can work in web?

**Comment by JohnGalt1717** [comment]
It should work right now with audio. Are you not seeing that?

**Comment by salime45** [comment]
We tested in Chrome and it doesn't ask for permissions, it just saves a video without audio. Neither audio nor video works in Firefox.

**Comment by JohnGalt1717** [comment]
Ok, should be working. The spec on this functionality is very bad. Appears that audio doesn't work right at all, so I had to approach it a different way.

This works for Chromium and Firefox. I haven't tested it on Safari as I have no way to do so.

It falls back from h265 to h264 to vp9 to vp8 to opus in that order depending on what is supported by the browser.

Might want to consider requested order of codecs for the future in the platform interface so that we can let users decide the order of importance they want and then we can negotiate based on what the platform supports and the user wants in that order. Could be an optional list on the record methods.

**Comment by salime45** [comment]
Hi @JohnGalt1717 ,

Sorry for the late again, i tried the app right now. Works perfectly in chrome and firefox.

**Comment by salime45** [comment]
Hi @JohnGalt1717 . Yo know if with this we can take screenshots in png format?

**Pull request merged**
