### PR TITLE
Add video dimensions api and update example

### PR DESCRIPTION
**Pull request by admarwick**
- Added `width` and `height` parameters to the methods `startRecordScreen` and `startRecordScreenAndAudio`. These new parameters determine the dimensions, and thus the file size, of the video file. These parameters do not affect the area of the screen that is recorded.
- Add code to example `main.dart` to show the use of the new parameters. Also updated README.md

Also updated the example to run with IOS 14 and recent Android versions, making several changes:

- Add usage descriptions to IOS example's Info.plist
- Changed example ios project format to be compatible with Xcode 12
- Updated xcodeproj utility
- Fixed the warning when running the example project on Android 10: “Your Flutter application is created using an older version of the Android embedding.” The fix requires following a documented series of changes.
- Note that to avoid errors like “Error launching application” when running the example on IOS 14 it is currently necessary to run Flutter from the stable channel, version >= 1.22.4. Running from the current dev or beta channels results in errors.
- Added doc comments for 'startRecordScreen' and 'startRecordScreenAndAudio'.

### CODE REVIEW

**Comment by pbajr** [comment]
Excited for this PR to be merged

**Comment by salime45** [comment]
We will review this the last week. Thanks for the work 🤙

**Review by 97loser — APPROVED** [review]

**Comment by admarwick** [comment]
Are there changes the team would like to see before merging this PR?

**Comment by mahdiyar-oraei** [comment]
Please merge this PR.

**Comment by gupta007vikas** [comment]
Hello Everyone, 
can anyone tell me if this issue is fixed. as I am still facing the same issue with latest version 1.1.1. I found two issues related to the same PR.
1- Video size is not capturing full screen.
2- Error for Audio

**Comment by jtmuller5** [comment]
Any idea when this will be merged? I'm running into a sizing issue on a Google Pixel 3.

**Comment by Lix-ai** [comment]
Waiting also for the merge for audio

**Comment by 97loser** [comment]
Please merge with audio.

**Comment by rstewart22** [comment]
Please merge this!

**Comment by admarwick** [comment]
It's not very hard to fork the repo then make the change yourself, then use
the new repo in your app.
 Let me know if you need more detailed steps.

Alan

**Pull request closed without merging**
